### ISSUE TITLE
Poster For Diwali

### ISSUE THREAD

**Issue by AnnelaViju** [GDSC-FCRIT/Hacktober-Design#2] opened 2023-10-13 08:02 UTC
Want to make a poster for Instagram story for Diwali festival. I will be using the brand kit available.

Please assign me this issue.

**Comment by NigeeHettige** [comment] 2023-10-13 17:50
Hi,
Can you assign me for this?

**Comment by DarrenDsouza7273** [comment] 2023-10-14 12:54
Hi @NigeeHettige as the issue is already assigned to someone else please check out the other available issues

**Closed as completed** 2023-10-15 18:19 UTC
Labels: good first issue, design, hacktoberfest
